#!/usr/bin/env bash
# Displays all running processes in a hierarchical and user-friendly format, including those without a TTY.

ps -axo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest
