#!/usr/bin/env bash
# shellcheck disable=SC2009

# Get the PID of the process
pid=$(ps -eo pid,cmd | grep "4-to_infinity_and_beyond" | grep -v grep | awk '{print $1}')

# Stop the process by sending SIGTERM via /proc
if [ -n "$pid" ]; then
  echo 15 > "/proc/$pid/oom_score_adj" 2>/dev/null
fi
