#!/usr/bin/env bash
# This script displays a message forever and ignores SIGTERM by saying "I am invincible!!!"

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
