#!/usr/bin/env bash
# shellcheck disable=SC2009

# Find the PID of the 7-highlander process
pid=$(ps -eo pid,cmd | grep "7-highlander" | grep -v grep | awk '{print $1}')

# If the PID was found, send SIGKILL (signal 9)
if [ -n "$pid" ]; then
  kill -9 "$pid"
fi
