#!/usr/bin/env bash
# This script displays "Best School" 10 times using a while loop,
# and displays "Hi" after the 9th iteration using an if statement.

count=1
while [ $count -le 10 ]
do
  echo "Best School"
  
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi

  count=$((count + 1))
done
