#!/usr/bin/env bash
# This script checks the status of the file named "school"

if [ -e "school" ]; then
    echo "File exist"

    if [ -f "school" ]; then
        echo "File exist and is a regular file"
    elif [ -d "school" ]; then
        echo "school exists but it’s a directory"
    fi

    if [ ! -s "school" ]; then
        echo "school exists but empty"
    fi
else
    echo "school doesn’t exist"
fi
